### ISSUE TITLE
Android incorrect b-64 credentialId

### ISSUE THREAD

**Issue by asimaranov** [f-23/react-native-passkey#24]
Function `PasskeyAndroid.register` transforms the returned `credentialId` from base64url to base64:
```js
  /**
   * Transform the attestation or assertion result
   */
  private static handleNativeResponse(
    response: PasskeyRegistrationResult & PasskeyAuthenticationResult
  ): PasskeyRegistrationResult & PasskeyAuthenticationResult {
    // Transform Base64URL Response to Base64
    let id = response.id;
    if (id.length % 4 !== 0) {
      id += '==='.slice(0, 4 - (id.length % 4));
    }
    id = id.replace(/-/g, '+').replace(/_/g, '/');

    return {
      ...response,
      id,
      rawId: id,
    };
  }
}
```

When this `credentialId` is used later in `authenticate`, it's still transformed to `base64` format while android expects `base64url`. Android fails to decode the credentialId if it ends with `==`: 
```
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: ebyf: java.lang.IllegalArgumentException: bad base-64
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at baoi.apply(:com.google.android.gms@234313039@23.43.13 (190408-577232161):43)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at ebua.d(:com.google.android.gms@234313039@23.43.13 (190408-577232161):3)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at ebub.run(:com.google.android.gms@234313039@23.43.13 (190408-577232161):139)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at ajlc.c(:com.google.android.gms@234313039@23.43.13 (190408-577232161):50)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at ajlc.run(:com.google.android.gms@234313039@23.43.13 (190408-577232161):76)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at ajqf.run(:com.google.android.gms@234313039@23.43.13 (190408-577232161):8)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at java.lang.Thread.run(Thread.java:1012)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: Caused by: java.lang.IllegalArgumentException: bad base-64
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at android.util.Base64.decode(Base64.java:163)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at android.util.Base64.decode(Base64.java:138)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at android.util.Base64.decode(Base64.java:120)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at com.google.android.gms.fido.fido2.api.common.PublicKeyCredentialDescriptor.b(:com.google.android.gms@234313039@23.43.13 (190408-577232161):15)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at com.google.android.gms.fido.fido2.api.common.PublicKeyCredentialRequestOptions.a(:com.google.android.gms@234313039@23.43.13 (190408-577232161):94)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at udq.a(:com.google.android.gms@234313039@23.43.13 (190408-577232161):14)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at baog.a(:com.google.android.gms@234313039@23.43.13 (190408-577232161):7)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at ebug.d(:com.google.android.gms@234313039@23.43.13 (190408-577232161):3)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	at ebui.run(:com.google.android.gms@234313039@23.43.13 (190408-577232161):42)
11-06 11:48:26.170 12673 13701 W Auth.Api.Credentials: 	... 6 more
```

And returns error:

```
11-06 11:48:26.187 13250 13388 I ReactNativeJS: [login error]: Error: [checkSignatureIsValid]: Error: [Passkey authentication error]: {"error":"NoCredentials","message":"No viable credential is available for the user."}
```

Possible fixes: Return rawId with value returned by platform to use it in `authenticate`. Add base64 to base64url credentialId transformation based on current platform in `authenticate`

**Comment by f-23** [comment]
Hi @asimaranov 

thank you for bringing this up!
I'll have a look at it.
